apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aji7788/argocdtest.git
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: mytest

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

