apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdtest
  labels:
    app: mine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mine
  template:
    metadata:
      labels:
        app: mine
    spec:
      containers:
      - name: nanaimage
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: mine
  ports:
    - protocol: TCP
      port: 80

